services:
  goapp:
    container_name: goapp 
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: postgres://postgress:postgress@db:5432/postgress
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: postgress
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}

